### ISSUE TITLE
Cannot find module 'jest-cli/bin/jest

### ISSUE THREAD

**Issue by guysaar223** [teambit/bit-envs#69]
tests fails on version 0reproduce, but  works fine on version **0.0.26**,

to reproduce:
1. download the tar
2. npm i / yarn 
3. bit build
4. bit test 

error:
```
error: bit failed to test pagination-link with the following exception:
Cannot find module 'jest-cli/bin/jest'
Error: Cannot find module 'jest-cli/bin/jest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at privateRequire (/Users/guysaar/Documents/PROJECT-RESOLVE-MODULES/50projects/reactstrap/.bitTmp/private-require.js:3:24)
    at TesterExtension.action (/Users/guysaar/Documents/PROJECT-RESOLVE-MODULES/50projects/reactstrap/.git/bit/components/testers/jest/bit.test-envs/0.0.32/dist/src/jest/jest.js:36:28)
    at Component._callee8$ (/usr/local/lib/node_modules/bit-bin/dist/consumer/component/consumer-component.js:1311:43)
    at tryCatch (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/bit-bin/dist/consumer/component/consumer-component.js:343:191)
    at /usr/local/lib/node_modules/bit-bin/dist/consumer/component/consumer-component.js:343:437
```

the tar of the project (with bit.json and .bitmap) 
[reactstrap.tar.gz](https://github.com/teambit/bit-envs/files/2506089/reactstrap.tar.gz)

**Comment by GiladShoham** [comment]
@imsnif I guess that happens because there is no jest dependency in our env. 
I think we should add require in the jest.js file to jest / jest-cli to make sure the env comes with those and with specific versions

**Comment by imsnif** [comment]
This should be addressed by: https://github.com/teambit/bit-envs/pull/70
